apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-healing-k8s.fullname" . }}-metrics
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "self-healing-k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: {{ .Values.service.metrics.type }}
  ports:
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "self-healing-k8s.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-healing-k8s.fullname" . }}-alerts
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "self-healing-k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: alerts
spec:
  type: {{ .Values.service.alerts.type }}
  ports:
    - port: {{ .Values.service.alerts.port }}
      targetPort: alerts
      protocol: TCP
      name: alerts
  selector:
    {{- include "self-healing-k8s.selectorLabels" . | nindent 4 }}
